import { Product, Category } from "@/types";

export const mockCategories: Category[] = [
  { id: 1, name: "Electronics", slug: "electronics", image: "https://images.unsplash.com/photo-1498049794561-7780e7231661?w=400&h=300&fit=crop", productCount: 24 },
  { id: 2, name: "Fashion", slug: "fashion", image: "https://images.unsplash.com/photo-1445205170230-053b83016050?w=400&h=300&fit=crop", productCount: 38 },
  { id: 3, name: "Home & Living", slug: "home-living", image: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=400&h=300&fit=crop", productCount: 19 },
  { id: 4, name: "Beauty", slug: "beauty", image: "https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=400&h=300&fit=crop", productCount: 31 },
  { id: 5, name: "Sports", slug: "sports", image: "https://images.unsplash.com/photo-1517649763962-0c623066013b?w=400&h=300&fit=crop", productCount: 16 },
  { id: 6, name: "Kids & Baby", slug: "kids-baby", image: "https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?w=400&h=300&fit=crop", productCount: 22 },
];

export const mockProducts: Product[] = [
  {
    id: 1,
    name: "Wireless Bluetooth Headphones",
    slug: "wireless-bluetooth-headphones",
    description: "Premium sound quality with active noise cancellation. 30-hour battery life and foldable design for portability.",
    price: 279,
    compareAtPrice: 389,
    sku: "ELEC-001",
    stockQuantity: 45,
    status: "active",
    featured: true,
    category: mockCategories[0],
    images: [{ id: 1, url: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&h=600&fit=crop", altText: "Wireless Headphones", isPrimary: true }],
    avgRating: 0,
    reviewCount: 0,
  },
  {
    id: 2,
    name: "Men's Classic Ankara Shirt",
    slug: "mens-classic-ankara-shirt",
    description: "Vibrant Ankara print shirt, 100% cotton, perfect for any occasion. Available in multiple sizes.",
    price: 89,
    compareAtPrice: 129,
    sku: "FASH-001",
    stockQuantity: 60,
    status: "active",
    featured: true,
    category: mockCategories[1],
    images: [{ id: 2, url: "https://images.unsplash.com/photo-1620012253295-c15cc3e65df4?w=600&h=600&fit=crop", altText: "Ankara Shirt", isPrimary: true }],
    avgRating: 0,
    reviewCount: 0,
  },
  {
    id: 3,
    name: "Smart Blender Pro",
    slug: "smart-blender-pro",
    description: "6-speed settings, 1.5L BPA-free jar. Perfect for smoothies, soups and baby food.",
    price: 199,
    compareAtPrice: null,
    sku: "HOME-001",
    stockQuantity: 30,
    status: "active",
    featured: true,
    category: mockCategories[2],
    images: [{ id: 3, url: "https://images.unsplash.com/photo-1570222094114-d054a817e56b?w=600&h=600&fit=crop", altText: "Smart Blender", isPrimary: true }],
    avgRating: 0,
    reviewCount: 0,
  },
  {
    id: 4,
    name: "Ladies Skincare Gift Set",
    slug: "ladies-skincare-gift-set",
    description: "Complete 5-piece skincare routine set. Cleanser, toner, serum, moisturizer and SPF30 sunscreen.",
    price: 229,
    compareAtPrice: 299,
    sku: "BEAU-001",
    stockQuantity: 25,
    status: "active",
    featured: true,
    category: mockCategories[3],
    images: [{ id: 4, url: "https://images.unsplash.com/photo-1556228578-8c89e6adf883?w=600&h=600&fit=crop", altText: "Skincare Set", isPrimary: true }],
    avgRating: 0,
    reviewCount: 0,
  },
  {
    id: 5,
    name: "Running Sneakers Ultra",
    slug: "running-sneakers-ultra",
    description: "Lightweight breathable mesh upper, cushioned sole. Ideal for everyday training and casual wear.",
    price: 349,
    compareAtPrice: 459,
    sku: "SPRT-001",
    stockQuantity: 50,
    status: "active",
    featured: true,
    category: mockCategories[4],
    images: [{ id: 5, url: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&h=600&fit=crop", altText: "Running Sneakers", isPrimary: true }],
    avgRating: 0,
    reviewCount: 0,
  },
  {
    id: 6,
    name: "4K Action Camera",
    slug: "4k-action-camera",
    description: "Waterproof up to 30m, 4K 60fps video, built-in WiFi. Includes mounting accessories.",
    price: 489,
    compareAtPrice: 589,
    sku: "ELEC-002",
    stockQuantity: 18,
    status: "active",
    featured: true,
    category: mockCategories[0],
    images: [{ id: 6, url: "https://images.unsplash.com/photo-1502920917128-1aa500764cbd?w=600&h=600&fit=crop", altText: "Action Camera", isPrimary: true }],
    avgRating: 0,
    reviewCount: 0,
  },
  {
    id: 7,
    name: "Toddler Ride-On Toy",
    slug: "toddler-ride-on-toy",
    description: "Safe and sturdy ride-on car for kids 1–3 years. Push handle included for parent control.",
    price: 159,
    compareAtPrice: 199,
    sku: "KIDS-001",
    stockQuantity: 22,
    status: "active",
    featured: true,
    category: mockCategories[5],
    images: [{ id: 7, url: "https://images.unsplash.com/photo-1566140967404-b8b3932483f5?w=600&h=600&fit=crop", altText: "Ride-On Toy", isPrimary: true }],
    avgRating: 0,
    reviewCount: 0,
  },
  {
    id: 8,
    name: "Premium Coffee Table",
    slug: "premium-coffee-table",
    description: "Solid wood frame with tempered glass top. Minimalist design that suits any living room.",
    price: 569,
    compareAtPrice: null,
    sku: "HOME-002",
    stockQuantity: 8,
    status: "active",
    featured: true,
    category: mockCategories[2],
    images: [{ id: 8, url: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=600&h=600&fit=crop", altText: "Coffee Table", isPrimary: true }],
    avgRating: 0,
    reviewCount: 0,
  },
];
